### PR TITLE
Add support for the HDF5 based GYRE stellar models 

### PR DESCRIPTION
**Pull request by VincentVanlaer**
This patch adds support for reading, writing and converting to and from GYRE stellar models stored as HDF5. The main changes are:

- 2 preparatory commits making development easier (I can move those to a separate PR if desired)
- Addition of the AbstractGYREStellarModel and HDF5GYREStellarModel classes. The AbstractGYREStellarModel class contains code that can be shared between GYREStellarModel and HDF5GYREStellarModel.
- Renaming the columns of the header and data numpy array of GYREStellarModel to match HDF5 dataset/attribute names

Let me know whether this approach is acceptable and I will do some final touches.

#### TODO
- [ ] Update docstrings (and potential other documentation?)
- [ ] Add some loading & conversion tests

### CODE REVIEW

**Comment by warrickball** [comment]
Hi! First, thanks for the contribution! These look like good changes. The smaller initial changes look excellent. I was wary of adding dependencies but `h5py` looks quite small, stable and robust. If it becomes a nuisance later, we can always somehow demote it to an optional dependency.

I'm not completely sold on the interface for converting between formats the plain-text and HDF5 formats. My overall concept was having one `to_file` function for a given format. Instead, the current changes also introduce 
```python
   GYREStellarModel.to_gsm(...)
   HDF5GYREStellarModel.to_plain(...)
```
which both write to files, where what I really expect is for those functions to return an object the other kind of model. So if I wanted to convert an HDF5 file to a plain-text file, I'd expect something like
```python
   HDF5GYREStellarModel.to_plain().to_file(filename)
```
I think `HDF5GYREStellarModel.to_plain()` does most of the work for this anyway. You should be able to just pass the arrays to the `GYREStellarModel` constructor instead of writing a file.

I say this knowing that I might be misunderstanding how HDF5 data actually works. I mentally have the paradigm of loading data into memory but realise that might not be appropriate for HDF5. This looks evident from `HDF5GYREStellarModel.to_file(...)`, which just copies the HDF5 file.

An alternative interface would have the user only interact through a class (like the `AbstractGYREStellarModel`) that is agnostic to whether the data is still on disk in an HDF5 file or in memory after being loaded from plain text. In that case, I could see an interface in which `load_gyre` and `load_gsm` both return the same kind of object, which is written to file with an argument to specify the format
```python
    AbstractGYREStellarModel.to_file(filename, fmt='HDF5') # or 'TXT'
```
Your basic step of renaming the plain-text headers to match the HDF5 ones already helps.

If we stick with separate classes, I'd suggest renaming `GYREStellarModel` to `PlainGYREStellarModel` or similar, for parity with `HDF5GYREStellarModel`. This isn't ideal but arguably a side effect of MESA and GYRE disagreeing on what to call this plain-text format... (MESA calls it GYRE format; GYRE calls it MESA format.)

Otherwise, as you've already noted, the main thing missing are some loading and conversion tests. Once the conversion works, I can also run my cross check that GYRE gives the same frequencies (within machine error) no matter how the equilibrium model is stored. 

It'll be better to propose changes to other docs in separate PRs.

Longer term, with `h5py` bundled, it might be neat to support GYRE's HDF5 *output* too.

**Comment by warrickball** [comment]
Now that I've dwelt on this, I actually think what you've implemented is almost the same as the interface I describe where the user doesn't have to worry about whether their data source is plain text or HDF5. I think the only changes required are to rename:
* `HDF5GYREStellarModel.to_file` to `HDF5GYREStellarModel.to_gsm`, and
* `GYREStellarModel.to_file` to `GYREStellarModel.to_plain`.

Then, however the user loaded the model, that's how they choose an output format. This could equivalently be implemented like `.to_file(..., fmt='HDF5')` but that would call/implement something like `.to_gsm(...)` anyway. We can consider such a `.to_file` function consider after this PR.

**Comment by VincentVanlaer** [comment]
One of the ways HDF5 is different is that data is not necessarily loaded into memory immediately, but can be loaded on demand, which can be more efficient when working with large datasets. This is why I made them separate classes. However, the resulting object does not support the full set of operations one would expect from a numpy array. For example `f['some_dataset'] - 1` will error, and you need to do `f['some_dataset'][:] - 1`, which wraps the dataset in a numpy array (I believe without copying the data though). 

It also occurred to me that modifying the data will either not work (the file has been opened read only) or modify the data in the file directly. Since the other formats don't do this, it would probably be better to properly convert the data to a structured numpy array. If someone wants to use HDF5 fully, then they can load the file themselves, since it's just one line.

**Comment by warrickball** [comment]
I didn't realise I had to authorise the tests again. It looks like you haven't uploaded the new data file for the HDF5 tests. 

There's also a failure on Python 3.6 but that's because it's been dropped from the Ubuntu 22.04 image. I've removed it from the test matrix and added Python 3.11 while at it.

**Comment by VincentVanlaer** [comment]
I rebased on master to pick up the changes to the tests and I added the missing files.

**Comment by warrickball** [comment]
Thanks! This looks ready to merge. I think the Python 3.11 failure is because [there aren't wheels for `h5py` in 3.11 yet](https://github.com/h5py/h5py/issues/2146), so the build fails because the runner hasn't installed the HDF5 library and can't build from source. I'll tinker with the testing in a separate PR.

**Pull request merged**
